title: Joona Väänänen
logo: "/images/logo.png"
description: >
  <br><br>
  Web Developer at Crasman
  <br><br>
  <a href="https://www.linkedin.com/in/joona-vaananen/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
